"""empty message

Revision ID: adfa38134161
Revises: 33d0743bec3d
Create Date: 2024-08-23 21:46:02.806460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfa38134161'
down_revision: Union[str, None] = '33d0743bec3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('year_ended', sa.Integer(), nullable=True))
    op.drop_column('natural_gas_utilization_by_sectors', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('natural_gas_utilization_by_sectors', 'year_ended')
    # ### end Alembic commands ###
