"""empty message

Revision ID: b2283365b0a0
Revises: f2c5c9bc6d73
Create Date: 2024-08-15 20:40:27.056250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2283365b0a0'
down_revision: Union[str, None] = 'f2c5c9bc6d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('abbreviated_names_and_acquisitions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'abbreviated_names_and_acquisitions')
    # ### end Alembic commands ###
