"""empty message

Revision ID: d95681946a51
Revises: adfa38134161
Create Date: 2024-08-23 21:48:00.761340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95681946a51'
down_revision: Union[str, None] = 'adfa38134161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitive_bid_rounds', sa.Column('year_ended', sa.Date(), nullable=True))
    op.drop_column('competitive_bid_rounds', 'date')
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('natural_gas_utilization_by_sectors', 'year_ended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('year_ended', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('natural_gas_utilization_by_sectors', 'date')
    op.add_column('competitive_bid_rounds', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('competitive_bid_rounds', 'year_ended')
    # ### end Alembic commands ###
