"""Added account table

Revision ID: edd0a4e69358
Revises: ce633b483f2c
Create Date: 2024-07-30 19:46:54.459491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd0a4e69358'
down_revision: Union[str, None] = 'ce633b483f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_gas_production_by_companies', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('natural_gas_production_by_companies_company_fkey', 'natural_gas_production_by_companies', type_='foreignkey')
    op.create_foreign_key(None, 'natural_gas_production_by_companies', 'companies', ['company_id'], ['id'])
    op.drop_column('natural_gas_production_by_companies', 'company')
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.drop_constraint('natural_gas_utilization_by_sectors_sector_fkey', 'natural_gas_utilization_by_sectors', type_='foreignkey')
    op.create_foreign_key(None, 'natural_gas_utilization_by_sectors', 'sectors', ['sector_id'], ['id'])
    op.drop_column('natural_gas_utilization_by_sectors', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natural_gas_utilization_by_sectors', sa.Column('sector', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'natural_gas_utilization_by_sectors', type_='foreignkey')
    op.create_foreign_key('natural_gas_utilization_by_sectors_sector_fkey', 'natural_gas_utilization_by_sectors', 'sectors', ['sector'], ['id'])
    op.drop_column('natural_gas_utilization_by_sectors', 'sector_id')
    op.add_column('natural_gas_production_by_companies', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'natural_gas_production_by_companies', type_='foreignkey')
    op.create_foreign_key('natural_gas_production_by_companies_company_fkey', 'natural_gas_production_by_companies', 'companies', ['company'], ['id'])
    op.drop_column('natural_gas_production_by_companies', 'company_id')
    # ### end Alembic commands ###
