"""empty message

Revision ID: f2c5c9bc6d73
Revises: edd0a4e69358
Create Date: 2024-07-30 20:04:51.489960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c5c9bc6d73'
down_revision: Union[str, None] = 'edd0a4e69358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'comments')
    # ### end Alembic commands ###
